### ISSUE TITLE
Compilation Error with CUDA: Invalid Value for --gpu-architecture on RTX 4090

### ISSUE THREAD

**Issue by xkuan** [jokofa/JAMPR_plus#2]
Hello,

I'm trying to run the JAMPR_plus project on my system which has an NVIDIA GeForce RTX 4090 GPU. However, I encountered a runtime error related to the CUDA GPU architecture setting. The error message is as follows:

`RuntimeError: nvrtc: error: invalid value for --gpu-architecture (-arch)`

It seems that the CUDA compilation does not correctly specify the GPU architecture for my GPU, which should be Compute Capability 8.9. I have checked the code but could not find where the GPU architecture is explicitly set for the CUDA compilations.

Could you please help me identify where and how I can specify the correct GPU architecture settings in the project? Or if there's an existing way to configure this that I might have missed, could you point me in the right direction?

Thank you very much for your assistance!

Best regards,
xkuan

**Comment by jokofa** [comment]
Hi, 

I noticed that you just closed the issue. Could you resolve your problems with the GPU architecture??
In that case I think it would be valuable for other future users to know how you were able to fix it. 
Unfortunately I currently do not have any access to a 4090 or similar to reproduce the error.

**Comment by xkuan** [comment]
Hi，

I guess it was the pytorch version, and I ended up using my own conda environment with an updated version of torch: 2.2.0+cu121.

By the way, I have another question to ask you now. After I trained a JAMPR model, even though I enforced `test_env_cfg["num_samples"] = 100` in the code during the test phase, the model did not sample. What should I do, please?

**Comment by jokofa** [comment]
In the config file at [config/meta/train.yaml](config/meta/train.yaml)
there are two parameters in the  evaluation (=inference) configuration which have to be adapted:

```
# test-set evaluation
tester_cfg:
  ...
  sampling: False  # < -- set to True
  num_samples: 10  # <-- set to integer number of samples the model should do
``` 
  
  did you set the "sampling" flag, too?

**Comment by xkuan** [comment]
Oh, I forgot it! Thanks for the tip!

**Comment by xkuan** [comment]
Oh, I forgot it! Thanks for the tip!
